name: "terraform-deploy"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_USER_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_USER_SECRET }}
      AWS_DEFAULT_REGION: eu-west-2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: |
          rm -rf .terraform
          terraform init
        working-directory: "./01_hello_world"

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -no-color
        working-directory: "./01_hello_world"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: "./01_hello_world"

      # - name: Terraform Destroy
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: terraform destroy -auto-approve
      #   working-directory: "./01_hello_world"
